name: Run Layout Verification

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  verification:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

        # can also specify python version if needed
      - name: setup python
        uses: actions/setup-python@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout SiEPIC siepic_ebeam_pdk
          python -m pip install --upgrade SiEPIC
          
      - name: run example layout verification
        #run: python "Example - Ring_resonator_sweep.py"
        run: python run_verification.py

      - name: Commit and push changes
        run: |
          git config --local user.email "jasminabrar@users.noreply.github.com"
          git config --local user.name "jasminabrar"
          if ! git diff --quiet; then
            git add /home/runner/work/edX-course-submission/edX-course-submission/ebeam_adiabatic_te1550.lyrdb
            git commit -m "Add layout check output for ebeam_adiabatic_te1550.gds"
            git push
          else
            echo "No changes to commit. Skipping commit and push."
          fi

