name: Run Layout Verification

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.gds'
    branches:
      - main


jobs:
  verification:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

        # can also specify python version if needed
      - name: setup python
        uses: actions/setup-python@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout SiEPIC siepic_ebeam_pdk
          python -m pip install --upgrade SiEPIC
          
      - name: get .gds file and run example layout verification
        id: run-script
        run: |
        
          #locate the .gds file and set as environment variable
          export GDS_FILE=$(find . -type f -name "*.gds" -exec basename {} \; | head -n 1)
          echo "GDS_FILE=$GDS_FILE" >> $GITHUB_ENV

          # print the name of the .gds file
          echo "GDS File: $GDS_FILE"
        
          # run layout verification
          python run_verification.py "$GDS_FILE"

      - name: Extract GDS File Name
        run: |
          # Extract the name without extension
          GDS_FILE_NAME=$(echo "$GDS_FILE" | sed 's/\.gds$//')
          echo "GDS_FILE_NAME=$GDS_FILE_NAME" >> $GITHUB_ENV

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: layout-errors
          path: /home/runner/work/edX-course-submission/edX-course-submission/${GDS_FILE_NAME}.lyrdb

      - name: fail if there are errors from layout verification
        run: |
          errors="${{ steps.run-script.outputs.result }}"
          if [[ $errors -gt 0 ]]; then
            echo "$errors errors detected. Please review error log uploaded as an artifact for this actions run."
            exit 1
          else
            echo "No errors detected."
          fi


