name: Run Layout Verification

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  verification:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

        # can also specify python version if needed
      - name: setup python
        uses: actions/setup-python@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout SiEPIC siepic_ebeam_pdk
          python -m pip install --upgrade SiEPIC
          
      - name: run example layout verification
        run: python "Example - Ring_resonator_sweep.py"

      - name: Commit and push changes
        run: |
          git config --global user.email "jasminabrar@users.noreply.github.com"
          git config --global user.name "jasminabrar"
          git add /home/runner/work/edX-course-submission/edX-course-submission/Test_structures_ring_resonators.lyrdb
          git commit -m "Add layout check output"
          git push


