name: Run Layout Verification

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.gds'
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  verification:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

        # can also specify python version if needed
      - name: setup python
        uses: actions/setup-python@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout SiEPIC siepic_ebeam_pdk
          python -m pip install --upgrade SiEPIC
          
      - name: get .gds file and run example layout verification
        id: run-script
        run: |
        
          #locate the .gds files and set as environment variable
          export GDS_FILES=$(find . -type f -name "*.gds" -exec basename {} \;)
          echo "GDS_FILES=$GDS_FILES" >> $GITHUB_ENV

          # print the name of the .gds files
          echo "GDS Files: $GDS_FILES"
        
          IFS=$'\n'
          
          # run layout verification on each .gds file
          for file in $GDS_FILES; do
            echo "File: $file"
            python run_verification.py "$file"
          done

      - name: Extract GDS File Name
        run: |
          # Extract the name without extension
          GDS_FILE_NAME=$(echo "$GDS_FILE" | sed 's/\.gds$//')
          echo "GDS_FILE_NAME=$GDS_FILE_NAME" >> $GITHUB_ENV

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: layout-errors
          path: /home/runner/work/edX-course-submission/edX-course-submission/

      - name: fail if there are errors from layout verification
        run: |
          errors="${{ steps.run-script.outputs.result }}"
          if [[ $errors -gt 0 ]]; then
            echo "$errors errors detected. Please review error log uploaded as an artifact for this actions run."
            exit 1
          else
            echo "No errors detected."
          fi


